-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE nfts_by_blockchain_blocks ADD
-- FOREIGN KEY (blockchain_block_hash) REFERENCES blockchain_block(hash);
--
-- ALTER TABLE nfts_by_blockchain_blocks ADD
-- FOREIGN KEY (nft_id) REFERENCES nft(id);
