-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE nft_ownership ALTER COLUMN block_number TYPE bigint USING block_number::bigint;
