version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      # expose to a port that wont conflict with other projects
      - 5442:5432
  graphql-engine:
    # note that we use cli-migrations-v3 which needed to be there to
    # apply migrations
    image: hasura/graphql-engine:v2.0.9.cli-migrations-v3
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://johndoe:randompassword@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://johndoe:randompassword@postgres:5432/postgres
      ## thin env var can be used to add the "default" database connection to Hasura.
      HASURA_GRAPHQL_DATABASE_URL: postgres://johndoe:randompassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false' # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
    volumes:
      # map the local hasura migration & metadata dirs so that hasura
      # will pick those up.
      - ./migrations:/hasura-migrations
      - ./metadata:/hasura-metadata
volumes:
  postgres:
