module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './components/**/*.stories.{js,ts,jsx,tsx}',
  ],
  theme: {
    colors: {
      transparent: 'transparent',
      black: '#000',
      white: '#fff',
      gray: {
        100: '#f7f7f7',
        200: '#d8dad9',
        300: '#bbbbbb',
        400: '#d8dad9',
        500: '#7d8492',
        600: '#888888',
        700: '#666666',
        800: '#3b4151',
      },
      ltblue: '#eef7f6',
      blue: '#47aed7',
      forest: '#0a854c',
      green: '#d3e7dc',
      lime: '#66fecb',
      navy: '#336bad',
      orange: '#ee4116',
      orangred: '#d53810',
      peach: '#ffe1c5',
      pink: '#f7cdcf',
      red: '#e11e2e',
      ltred: '#feebeb',
      yellow: '#e2ba36',
    },
    extend: {},
  },
  plugins: [
    require('@tailwindcss/line-clamp'),
    require('@tailwindcss/typography'),
  ],
}
