-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- -- Cleanup obsolote tables, views, functions
-- DROP VIEW nft_asset_view;
-- DROP VIEW resource_view;
-- DROP FUNCTION add_nft;
-- DROP FUNCTION add_nft_metadata;
-- DROP FUNCTION add_other_nft_resource;
