-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- -- Make image_uri_hash non-nullable.
-- ALTER TABLE nft_metadata
--     ALTER COLUMN image_uri_hash SET NOT NULL;
