import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  console.log(process.env.NIFTYSAVE_API_ENDPOINT)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          <li>NIFTYSAVE_API_ENDPOINT</li>
          <li>{`${process.env.NIFTYSAVE_API_ENDPOINT}`}</li>
        </ul>
      </main>
    </div>
  )
}
