--
-- PostgreSQL database dump
--

-- Dumped from database version 13.3
-- Dumped by pg_dump version 13.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO postgres;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: pin_status_type; Type: TYPE; Schema: public; Owner: supabase_admin
--

CREATE TYPE public.pin_status_type AS ENUM (
    'processing',
    'queued',
    'pinning',
    'pinned',
    'failed'
);


ALTER TYPE public.pin_status_type OWNER TO supabase_admin;

--
-- Name: service_type; Type: TYPE; Schema: public; Owner: supabase_admin
--

CREATE TYPE public.service_type AS ENUM (
    'PINATA',
    'IPFS_CLUSTER'
);


ALTER TYPE public.service_type OWNER TO supabase_admin;

--
-- Name: upload_pin_type; Type: TYPE; Schema: public; Owner: supabase_admin
--

CREATE TYPE public.upload_pin_type AS (
	status public.pin_status_type,
	service public.service_type,
	error text
);


ALTER TYPE public.upload_pin_type OWNER TO supabase_admin;

--
-- Name: upload_return_type; Type: TYPE; Schema: public; Owner: supabase_admin
--

CREATE TYPE public.upload_return_type AS (
	id bigint,
	cid text,
	size bigint
);


ALTER TYPE public.upload_return_type OWNER TO supabase_admin;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: uploads; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.uploads (
    id bigint NOT NULL,
    issuer text NOT NULL,
    key_id bigint,
    cid text,
    type text NOT NULL,
    files jsonb,
    inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);


ALTER TABLE public.uploads OWNER TO supabase_admin;

--
-- Name: upload(json); Type: FUNCTION; Schema: public; Owner: supabase_admin
--

CREATE FUNCTION public.upload(data json) RETURNS SETOF public.uploads
    LANGUAGE plpgsql
    AS $$

declare
  inserted_content contents%rowtype;
  inserted_upload uploads%rowtype;
  result upload_return_type;
BEGIN

insert into contents (cid, size)
  values (data->>'cid', (data->>'size')::int)
  ON CONFLICT ( cid ) DO NOTHING
  returning * into inserted_content;

insert into uploads ( issuer, key_id, cid, type, files )
  values (
    data->>'issuer', 
    (data->>'key_id')::int, 
    data->>'cid', 
    data->>'type',
    (data->>'files')::jsonb
  )
  ON CONFLICT ( issuer, cid ) DO NOTHING
  returning * into inserted_upload;


insert into pins (cid, status, service, error)
  select data->>'cid', status, service, error 
  from json_populate_recordset(null::upload_pin_type, (data->>'pins')::json)
  on conflict (cid, service) do nothing;

--raise exception 'upload % content % ', inserted_upload.id, inserted_content.cid;

return query select * 
from uploads u
where u.issuer = data->>'issuer' AND u.cid = data->>'cid';

IF NOT FOUND THEN
    RAISE EXCEPTION 'No upload found %', data->>'cid';
END IF;

RETURN;

END
$$;


ALTER FUNCTION public.upload(data json) OWNER TO supabase_admin;

--
-- Name: account_keys; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.account_keys (
    key_id bigint NOT NULL,
    name text NOT NULL,
    secret text NOT NULL,
    issuer text NOT NULL,
    inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);


ALTER TABLE public.account_keys OWNER TO supabase_admin;

--
-- Name: account_keys_key_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.account_keys ALTER COLUMN key_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_keys_key_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.accounts (
    issuer text NOT NULL,
    sub text NOT NULL,
    name text NOT NULL,
    picture text,
    github text,
    email text NOT NULL,
    public_address text NOT NULL,
    inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);


ALTER TABLE public.accounts OWNER TO supabase_admin;

--
-- Name: contents; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.contents (
    cid text NOT NULL,
    size bigint,
    inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);


ALTER TABLE public.contents OWNER TO supabase_admin;

--
-- Name: pins; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.pins (
    pin_id bigint NOT NULL,
    status public.pin_status_type NOT NULL,
    cid text NOT NULL,
    service public.service_type NOT NULL,
    error text,
    inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);


ALTER TABLE public.pins OWNER TO supabase_admin;

--
-- Name: pins_pin_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.pins ALTER COLUMN pin_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pins_pin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: uploads_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.uploads ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.uploads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_keys account_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.account_keys
    ADD CONSTRAINT account_keys_pkey PRIMARY KEY (key_id);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (issuer);


--
-- Name: accounts accounts_public_address_key; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_public_address_key UNIQUE (public_address);


--
-- Name: accounts accounts_sub_key; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_sub_key UNIQUE (sub);


--
-- Name: contents contents_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.contents
    ADD CONSTRAINT contents_pkey PRIMARY KEY (cid);


--
-- Name: pins pins_cid_service_key; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.pins
    ADD CONSTRAINT pins_cid_service_key UNIQUE (cid, service);


--
-- Name: pins pins_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.pins
    ADD CONSTRAINT pins_pkey PRIMARY KEY (pin_id);


--
-- Name: uploads uploads_issuer_cid_key; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.uploads
    ADD CONSTRAINT uploads_issuer_cid_key UNIQUE (issuer, cid);


--
-- Name: uploads uploads_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.uploads
    ADD CONSTRAINT uploads_pkey PRIMARY KEY (id);


--
-- Name: account_keys account_keys_issuer_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.account_keys
    ADD CONSTRAINT account_keys_issuer_fkey FOREIGN KEY (issuer) REFERENCES public.accounts(issuer);


--
-- Name: pins pins_cid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.pins
    ADD CONSTRAINT pins_cid_fkey FOREIGN KEY (cid) REFERENCES public.contents(cid);


--
-- Name: uploads uploads_cid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.uploads
    ADD CONSTRAINT uploads_cid_fkey FOREIGN KEY (cid) REFERENCES public.contents(cid);


--
-- Name: uploads uploads_issuer_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.uploads
    ADD CONSTRAINT uploads_issuer_fkey FOREIGN KEY (issuer) REFERENCES public.accounts(issuer);


--
-- Name: uploads uploads_key_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.uploads
    ADD CONSTRAINT uploads_key_id_fkey FOREIGN KEY (key_id) REFERENCES public.account_keys(key_id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;


--
-- Name: TABLE uploads; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.uploads TO postgres;
GRANT ALL ON TABLE public.uploads TO anon;
GRANT ALL ON TABLE public.uploads TO authenticated;
GRANT ALL ON TABLE public.uploads TO service_role;


--
-- Name: FUNCTION upload(data json); Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON FUNCTION public.upload(data json) TO postgres;
GRANT ALL ON FUNCTION public.upload(data json) TO anon;
GRANT ALL ON FUNCTION public.upload(data json) TO authenticated;
GRANT ALL ON FUNCTION public.upload(data json) TO service_role;


--
-- Name: TABLE account_keys; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.account_keys TO postgres;
GRANT ALL ON TABLE public.account_keys TO anon;
GRANT ALL ON TABLE public.account_keys TO authenticated;
GRANT ALL ON TABLE public.account_keys TO service_role;


--
-- Name: SEQUENCE account_keys_key_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.account_keys_key_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.account_keys_key_id_seq TO anon;
GRANT ALL ON SEQUENCE public.account_keys_key_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.account_keys_key_id_seq TO service_role;


--
-- Name: TABLE accounts; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.accounts TO postgres;
GRANT ALL ON TABLE public.accounts TO anon;
GRANT ALL ON TABLE public.accounts TO authenticated;
GRANT ALL ON TABLE public.accounts TO service_role;


--
-- Name: TABLE contents; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.contents TO postgres;
GRANT ALL ON TABLE public.contents TO anon;
GRANT ALL ON TABLE public.contents TO authenticated;
GRANT ALL ON TABLE public.contents TO service_role;


--
-- Name: TABLE pins; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.pins TO postgres;
GRANT ALL ON TABLE public.pins TO anon;
GRANT ALL ON TABLE public.pins TO authenticated;
GRANT ALL ON TABLE public.pins TO service_role;


--
-- Name: SEQUENCE pins_pin_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.pins_pin_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.pins_pin_id_seq TO anon;
GRANT ALL ON SEQUENCE public.pins_pin_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.pins_pin_id_seq TO service_role;


--
-- Name: SEQUENCE uploads_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.uploads_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.uploads_id_seq TO anon;
GRANT ALL ON SEQUENCE public.uploads_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.uploads_id_seq TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES  TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES  TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES  TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public REVOKE ALL ON SEQUENCES  FROM supabase_admin;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES  TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES  TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES  TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES  TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE ALL ON FUNCTIONS  FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS  TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS  TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS  TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public REVOKE ALL ON FUNCTIONS  FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public REVOKE ALL ON FUNCTIONS  FROM supabase_admin;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS  TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS  TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS  TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS  TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES  TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES  TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES  TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public REVOKE ALL ON TABLES  FROM supabase_admin;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES  TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES  TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES  TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES  TO service_role;


--
-- PostgreSQL database dump complete
--

