CREATE TYPE pin_status_type AS ENUM ('processing', 'queued', 'pinning', 'pinned', 'failed');
CREATE TYPE service_type AS ENUM ('PINATA', 'IPFS_CLUSTER');

CREATE TABLE IF NOT EXISTS accounts (
  issuer TEXT PRIMARY KEY,
  sub TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  picture TEXT,
  github TEXT,
  email TEXT NOT NULL,
  public_address TEXT NOT NULL unique,
  inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS account_keys (
  key_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  secret TEXT NOT NULL,
  issuer TEXT NOT NULL references accounts ( issuer ),
  inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS contents (
  cid TEXT PRIMARY KEY,
  size BIGINT,
  inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- remove pin_id
CREATE TABLE IF NOT EXISTS pins (
  pin_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status pin_status_type NOT NULL,
  cid text NOT NULL references contents ( cid ),
  service service_type NOT NULL,
  error text,
  inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (cid, service)
);

-- maybe we dont need this...
/*CREATE TABLE IF NOT EXISTS pin_locations (
  multiaddr text primary key,
  region text,
  pin_id bigint not null references pins ( pin_id ),
  inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);*/

-- TODO add files prop
-- removed_at and add the on conflict logic to the function, null or date depending on the situation
-- delete id not needed
-- check cid v1 or v0 logic 
CREATE TABLE IF NOT EXISTS uploads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  issuer TEXT NOT NULL references accounts ( issuer ),
  key_id bigint references account_keys ( key_id ),
  cid text references contents ( cid ),
  type text NOT NULL,
  files jsonb,
  inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (issuer, cid)
);

