
CREATE TYPE pin_status_type AS ENUM ('queued', 'pinning', 'pinned', 'failed');
CREATE TYPE service_type AS ENUM ('PINATA', 'IPFS_CLUSTER');

-- We still need to use "account" and not "user" here. To use "user" we can't use the public schema.
-- Using another schema besides public forces other changes in the types and client. 
-- We can do this after we settle on the schema and code.
CREATE TABLE IF NOT EXISTS account (
  issuer TEXT PRIMARY KEY,
  sub TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  picture TEXT,
  github TEXT,
  email TEXT NOT NULL,
  public_address TEXT NOT NULL unique,
  inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS auth_key (
  key_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  secret TEXT NOT NULL,
  issuer TEXT NOT NULL references account ( issuer ),
  inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS content (
  cid TEXT PRIMARY KEY,
  size int,
  inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS pin (
  pin_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status pin_status_type NOT NULL,
  cid text NOT NULL references content ( cid ),
  service service_type NOT NULL,
  inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (cid, service)
);

-- removed_at and add the on conflict logic to the function, null or date depending on the situation
-- check cid v1 or v0 logic 
CREATE TABLE IF NOT EXISTS upload (
  upload_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  issuer TEXT NOT NULL references account ( issuer ),
  key_id bigint references auth_key ( key_id ),
  cid text NOT NULL references content ( cid ),
  type text NOT NULL,
  files jsonb,
  origins jsonb,
  meta jsonb,
  name TEXT,
  inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (issuer, cid)
);

