GRANT USAGE ON SCHEMA public TO stats;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO stats;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO stats;

GRANT USAGE ON SCHEMA cargo TO stats;
GRANT SELECT ON ALL TABLES IN SCHEMA cargo TO stats;
ALTER DEFAULT PRIVILEGES IN SCHEMA cargo GRANT SELECT ON TABLES TO stats;
